// GENERATED by tool/sync_content_asset.sh — do not edit by hand.
//
// Identifies the content in assets/content.db, so that
// WirdiDatabaseFiles.ensureContentDatabase can tell an app update that brought
// new content from one that did not without reading the 4.6 MB asset to find
// out. test/data/real_content_db_test.dart fails if this goes stale.
// The value sits on its own line because dart format puts it there: the
// declaration does not fit in 80 columns, and CI checks formatting.
const String bundledContentStamp =
    '0.3.0 746ecf15e15090da994d6f06f0352633039650514f9c3d9c67429b566282ae99';
