// GENERATED by tool/sync_content_asset.sh — do not edit by hand.
//
// Identifies the content in assets/content.db, so that
// WirdiDatabaseFiles.ensureContentDatabase can tell an app update that brought
// new content from one that did not without reading the 4.6 MB asset to find
// out. test/data/real_content_db_test.dart fails if this goes stale.
// The value sits on its own line because dart format puts it there: the
// declaration does not fit in 80 columns, and CI checks formatting.
const String bundledContentStamp =
    '0.10.1 68295ec1920611f60d492ddc1421e5224530bd442f9542ecdfdfa4cea4aed352';
