#!/usr/bin/env bash
# Copy the built content database into the Flutter asset bundle.
#
#   python3 content/scripts/build_content.py   # -> content/build/content.db
#   tool/sync_content_asset.sh                 # -> assets/content.db
#
# assets/content.db is gitignored: it is a build artifact, reproducible from
# content/sources/ at any time.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/content/build/content.db"
dst="$root/assets/content.db"

if [[ ! -f "$src" ]]; then
  echo "no $src — run: python3 content/scripts/build_content.py" >&2
  exit 1
fi

python3 "$root/content/scripts/verify_content.py" --db "$src"
python3 "$root/tool/check_schema_parity.py" --db "$src"

cp "$src" "$dst"
echo "copied $(basename "$src") -> assets/content.db ($(du -h "$dst" | cut -f1))"

# The stamp the app compares the copy in its application support directory
# against, to decide whether an update brought new content with it.
#
# It cannot be the asset's byte length, which is what this used to be: SQLite
# allocates in 4 KB pages, so a fixed translation or an added note produces a
# file of exactly the same size, and the app would go on serving the old
# content after an update with nothing to show for it.
#
# content_version and content_checksum together, because neither alone is
# enough. The checksum is taken over the content rows with `meta` excluded, so
# it does not move when only the content version does; and built_at is in
# neither, so rebuilding unchanged sources does not force every user to take a
# copy again.
stamp="$(python3 - "$src" <<'PY'
import sqlite3, sys
meta = dict(sqlite3.connect(sys.argv[1]).execute("SELECT key, value FROM meta"))
print(f"{meta['content_version']} {meta['content_checksum']}")
PY
)"

cat > "$root/lib/data/content_stamp.dart" <<EOF
// GENERATED by tool/sync_content_asset.sh — do not edit by hand.
//
// Identifies the content in assets/content.db, so that
// WirdiDatabaseFiles.ensureContentDatabase can tell an app update that brought
// new content from one that did not without reading the 4.6 MB asset to find
// out. test/data/real_content_db_test.dart fails if this goes stale.
// The value sits on its own line because dart format puts it there: the
// declaration does not fit in 80 columns, and CI checks formatting.
const String bundledContentStamp =
    '$stamp';
EOF

echo "stamped lib/data/content_stamp.dart ($stamp)"
