import 'dart:async';

import 'package:flutter/foundation.dart' show debugPrint, listEquals;
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/timezone.dart' as tz;

import 'reminder_plan.dart';
import 'reminder_scheduler.dart';

/// Reminders as the phone's own local notifications.
///
/// Nothing leaves the device and nothing needs the network: the notification
/// is handed to the operating system with its text and its time, and the
/// operating system shows it. The only thing the app asks for is permission
/// to post notifications at all, and only when somebody turns a reminder on.
final class LocalNotificationScheduler implements ReminderScheduler {
  LocalNotificationScheduler._(this._plugin);

  /// Sets the plugin up without asking for anything.
  ///
  /// Every `request…Permission` flag is off: on iOS the defaults would put the
  /// system prompt in front of the first frame, for a feature the user has not
  /// touched and may never use.
  static Future<LocalNotificationScheduler> initialize() async {
    final FlutterLocalNotificationsPlugin plugin =
        FlutterLocalNotificationsPlugin();
    final LocalNotificationScheduler scheduler = LocalNotificationScheduler._(
      plugin,
    );
    await plugin.initialize(
      settings: const InitializationSettings(
        // A drawable rather than the launcher mipmap: Android draws the small
        // icon as a silhouette, and the full-colour launcher icon would be a
        // white square. Generated by tool/render_app_icons.py and kept from
        // the release shrinker by res/raw/keep.xml, since the only reference
        // to it is this string.
        android: AndroidInitializationSettings('ic_notification'),
        iOS: DarwinInitializationSettings(
          requestAlertPermission: false,
          requestSoundPermission: false,
          requestBadgePermission: false,
        ),
      ),
      onDidReceiveNotificationResponse: (NotificationResponse _) =>
          scheduler._taps.add(null),
    );
    return scheduler;
  }

  final FlutterLocalNotificationsPlugin _plugin;

  final StreamController<void> _taps = StreamController<void>.broadcast();

  /// Every replacement runs after the one before it has finished. Two syncs
  /// close together — a commit, then the sheet's own refresh — would
  /// otherwise interleave their cancels and schedules, and leave duplicates or
  /// gaps behind.
  Future<void> _queue = Future<void>.value();

  /// The plan last handed over in full, by this run of the app.
  ///
  /// The sync runs on every return from the player and the contents screen,
  /// and most of those change nothing. Each schedule is a call to the platform
  /// thread — on Android one that rewrites the plugin's whole stored list — so
  /// an unchanged plan is not sent again. Null at launch, so the first sync of
  /// every run always replaces what the phone holds: a force-stop on Android
  /// clears scheduled alarms, and this is what puts them back.
  List<PlannedReminder>? _scheduled;

  static const NotificationDetails _details = NotificationDetails(
    android: AndroidNotificationDetails(
      'reminders',
      'Reminders',
      channelDescription: 'The times you chose to be reminded of a wird',
      category: AndroidNotificationCategory.reminder,
      // No dot on the launcher icon. The app carries no badges and no counts
      // anywhere, and a reminder that has been seen is done with.
      channelShowBadge: false,
    ),
    iOS: DarwinNotificationDetails(presentBadge: false),
  );

  @override
  Future<bool> requestPermission() async {
    final AndroidFlutterLocalNotificationsPlugin? android = _plugin
        .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin
        >();
    if (android != null) {
      return await android.requestNotificationsPermission() ?? false;
    }
    final IOSFlutterLocalNotificationsPlugin? ios = _plugin
        .resolvePlatformSpecificImplementation<
          IOSFlutterLocalNotificationsPlugin
        >();
    if (ios != null) {
      // An alert and a sound. Not a badge: see [_details].
      return await ios.requestPermissions(alert: true, sound: true) ?? false;
    }
    return false;
  }

  @override
  Future<void> openSystemSettings() async {
    await _plugin.openAppNotificationSettings();
  }

  @override
  Future<void> replaceAll(List<PlannedReminder> reminders) {
    return _queue = _queue.then((_) => _replace(reminders));
  }

  Future<void> _replace(List<PlannedReminder> reminders) async {
    if (listEquals(reminders, _scheduled)) return;
    _scheduled = null;
    try {
      // Pending ones only. A reminder already sitting in the shade stays
      // there until it is tapped or swiped — taking it away because the app
      // was opened would be the app tidying up after the user.
      await _plugin.cancelAllPendingNotifications();
      for (final (int id, PlannedReminder reminder) in reminders.indexed) {
        // The plan was made a moment ago, and the plugin refuses a time that
        // has passed. A reminder for this very minute is not worth an error.
        if (!reminder.at.isAfter(DateTime.now())) continue;
        await _plugin.zonedSchedule(
          id: id,
          // An instant, in UTC. The plan already turned the reminder's clock
          // time into a moment on a particular local day, daylight saving and
          // all, and a UTC instant needs no time zone database to schedule.
          // A phone that changes time zone gets a new plan the next time the
          // app comes to the front.
          scheduledDate: tz.TZDateTime.from(reminder.at.toUtc(), tz.UTC),
          notificationDetails: _details,
          // Inexact: Android may hold it for a few minutes to batch it with
          // other wake-ups. Exact alarms need a permission Google Play keeps
          // for alarm clocks and calendars, and a reminder to recite a wird
          // is neither.
          androidScheduleMode: AndroidScheduleMode.inexactAllowWhileIdle,
          title: reminder.title,
          body: reminder.body,
        );
      }
      _scheduled = reminders;
    } catch (error, stackTrace) {
      // A reminder that fails to schedule is not worth taking the app down
      // over, and there is nothing on screen to tell. The next sync tries the
      // whole plan again.
      debugPrint('Wirdi could not schedule reminders: $error\n$stackTrace');
    }
  }

  @override
  Stream<void> get taps => _taps.stream;
}
